included:
  - Hookbot
  - HookbotWatch
  - HookbotTests
  - HookbotUITests
  - Shared

excluded:
  - build
  - DerivedData
  - .build

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - statement_position
  - function_parameter_count
  - static_over_final_class
  - trailing_comma
  - vertical_whitespace
  - large_tuple
  - nesting
  - type_name
  - force_cast
  - implicit_return
